#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Convert a bnx2x storm firmware file into an embeddable C header.

Usage: bnx2x_mkfw.py bnx2x-e2-7.13.21.0.fw > bnx2x_fw.h

The .fw container format is defined by the Linux driver's
bnx2x_fw_file_hdr.h: thirteen {be32 len, be32 offset} section records
(init_ops, init_ops_offsets, init_data, {t,u,c,x}sem int-table and
pram data, iro array, fw_version).

The transformations performed here mirror what the Linux driver does
at load time (bnx2x_main.c bnx2x_init_firmware()):

- init_data:        array of be32  -> native u32 array
- init_ops:         {op:8, offset:24, data:32} be32 pairs -> u32 pairs
                    ((op << 24) | offset, data) in native byte order
- init_ops_offsets: array of be16  -> native u16 array
- iro array:        {base:32, m1:16, m2:16, m3:16, size:16} big-endian
                    -> decoded struct array
- SEM int-table and pram sections: kept verbatim (they are gzip
  streams, decompressed on the fly by the OP_ZP init operation)

The firmware itself is redistributable; see the linux-firmware WHENCE
file and LICENCE.bnx2x.
"""

import os
import struct
import sys

SECTIONS = [
    "init_ops",
    "init_ops_offsets",
    "init_data",
    "tsem_int_table_data",
    "tsem_pram_data",
    "usem_int_table_data",
    "usem_pram_data",
    "csem_int_table_data",
    "csem_pram_data",
    "xsem_int_table_data",
    "xsem_pram_data",
    "iro_arr",
    "fw_version",
]


def emit_u32_array(name, values):
    print("static const uint32_t %s[%d] = {" % (name, len(values)))
    for i in range(0, len(values), 6):
        chunk = values[i:i + 6]
        print("\t" + " ".join("0x%08x," % v for v in chunk))
    print("};")
    print("")


def emit_u16_array(name, values):
    print("static const uint16_t %s[%d] = {" % (name, len(values)))
    for i in range(0, len(values), 8):
        chunk = values[i:i + 8]
        print("\t" + " ".join("0x%04x," % v for v in chunk))
    print("};")
    print("")


def emit_u8_array(name, data):
    print("static const uint8_t %s[%d] = {" % (name, len(data)))
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        print("\t" + " ".join("0x%02x," % b for b in chunk))
    print("};")
    print("")


def main():
    if len(sys.argv) != 2:
        sys.stderr.write(__doc__)
        sys.exit(1)
    with open(sys.argv[1], "rb") as f:
        blob = f.read()

    hdr = {}
    for i, name in enumerate(SECTIONS):
        length, offset = struct.unpack_from(">II", blob, i * 8)
        if offset + length > len(blob):
            sys.stderr.write("Section %s out of bounds\n" % name)
            sys.exit(1)
        hdr[name] = blob[offset:offset + length]
        sys.stderr.write("%-22s %6d bytes\n" % (name, length))

    version = hdr["fw_version"]
    ver_str = "%d.%d.%d.%d" % (version[0], version[1], version[2],
                               version[3])

    print("#ifndef _BNX2X_FW_H")
    print("#define _BNX2X_FW_H")
    print("")
    print("/** @file")
    print(" *")
    print(" * Broadcom/QLogic NetXtreme II storm firmware %s" % ver_str)
    print(" *")
    print(" * Generated by bnx2x_mkfw.py from %s" % os.path.basename(sys.argv[1]))
    print(" * from the linux-firmware collection.  Do not edit.")
    print(" *")
    print(" * Copyright (c) 2007-2011 Broadcom Corporation")
    print(" *")
    print(" * This file contains firmware data derived from proprietary")
    print(" * unpublished source code, Copyright (c) 2007-2011 Broadcom")
    print(" * Corporation.")
    print(" *")
    print(" * Permission is hereby granted for the distribution of this")
    print(" * firmware data in hexadecimal or equivalent format, provided")
    print(" * this copyright notice is accompanying it.")
    print(" *")
    print(" * (Licence text as per linux-firmware LICENCE.bnx2x.)")
    print(" *")
    print(" */")
    print("")
    print("#include <stdint.h>")
    print("")
    print("#define BNX2X_FW_MAJOR %d" % version[0])
    print("#define BNX2X_FW_MINOR %d" % version[1])
    print("#define BNX2X_FW_REV   %d" % version[2])
    print("#define BNX2X_FW_ENG   %d" % version[3])
    print("")

    # init_data: be32 -> u32
    data = hdr["init_data"]
    values = list(struct.unpack(">%dI" % (len(data) // 4), data))
    emit_u32_array("bnx2x_init_data", values)

    # init_ops: pairs of be32 -> ((op << 24) | offset, raw_data)
    data = hdr["init_ops"]
    values = list(struct.unpack(">%dI" % (len(data) // 4), data))
    emit_u32_array("bnx2x_init_ops", values)

    # init_ops_offsets: be16 -> u16
    data = hdr["init_ops_offsets"]
    values = list(struct.unpack(">%dH" % (len(data) // 2), data))
    emit_u16_array("bnx2x_init_ops_offsets", values)

    # iro array: 12-byte big-endian records
    data = hdr["iro_arr"]
    count = len(data) // 12
    print("static const struct bnx2x_iro bnx2x_iro_arr[%d] = {" % count)
    for i in range(count):
        base, m1m2, m3size = struct.unpack_from(">III", data, i * 12)
        print("\t{ 0x%08x, 0x%04x, 0x%04x, 0x%04x, 0x%04x }," %
              (base, (m1m2 >> 16) & 0xffff, m1m2 & 0xffff,
               (m3size >> 16) & 0xffff, m3size & 0xffff))
    print("};")
    print("")

    # SEM sections: raw gzip streams
    for sem in ("tsem", "usem", "csem", "xsem"):
        emit_u8_array("bnx2x_%s_int_table" % sem,
                      hdr["%s_int_table_data" % sem])
        emit_u8_array("bnx2x_%s_pram" % sem, hdr["%s_pram_data" % sem])

    print("#endif /* _BNX2X_FW_H */")


if __name__ == "__main__":
    main()
